framework:
  rate_limiter:
    anonymous_api:
      # use 'sliding_window' if you prefer that policy
      policy: 'sliding_window'
      limit: 10
      interval: '1 minute'
      # use the "cache.anonymous_rate_limiter" cache pool
      #cache_pool: 'cache.anonymous_rate_limiter'

    authenticated_api:
      policy: 'token_bucket'
      limit: 5000
      rate: { interval: '15 minutes', amount: 500 }